#!/bin/bash
# 测试 YashanDB 视图支持情况（Phase 1/2 指标）

YASQL="/data/yashan/install/23.4.7.100/bin/yasql"
CONN="sys/Cod-2022@127.0.0.1:1688"

echo "=========================================="
echo "YashanDB 23.4 视图支持测试"
echo "=========================================="

echo ""
echo "[1] V\$RESOURCE_LIMIT"
$YASQL $CONN -A -q -c "SELECT RESOURCE_NAME, CURRENT_UTILIZATION, MAX_UTILIZATION, LIMIT_VALUE FROM V\$RESOURCE_LIMIT;" 2>&1

echo ""
echo "[2] DBA_TABLESPACES (CONTENTS 列)"
$YASQL $CONN -A -q -c "SELECT TABLESPACE_NAME, CONTENTS, STATUS FROM DBA_TABLESPACES;" 2>&1

echo ""
echo "[3] DBA_TEMP_FILES"
$YASQL $CONN -A -q -c "SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES, AUTOEXTENSIBLE FROM DBA_TEMP_FILES;" 2>&1

echo ""
echo "[4] DBA_DATA_FILES (AUTOEXTENSIBLE)"
$YASQL $CONN -A -q -c "SELECT FILE_NAME, TABLESPACE_NAME, BYTES, MAXBYTES, AUTOEXTENSIBLE FROM DBA_DATA_FILES;" 2>&1

echo ""
echo "[5] V\$WAITCLASSMETRIC (等待类)"
$YASQL $CONN -A -q -c "SELECT WAIT_CLASS, TOTAL_WAITS, TIME_WAITED FROM V\$WAITCLASSMETRIC;" 2>&1

echo ""
echo "[6] V\$SYSTEM_WAIT_CLASS"
$YASQL $CONN -A -q -c "SELECT WAIT_CLASS, TOTAL_WAITS, TIME_WAITED FROM V\$SYSTEM_WAIT_CLASS;" 2>&1

echo ""
echo "[7] DBA_USERS (密码过期)"
$YASQL $CONN -A -q -c "SELECT USERNAME, ACCOUNT_STATUS, EXPIRY_DATE FROM DBA_USERS;" 2>&1

echo ""
echo "[8] V\$PARAMETER (STATISTICS_LEVEL)"
$YASQL $CONN -A -q -c "SELECT NAME, VALUE FROM V\$PARAMETER WHERE NAME='statistics_level';" 2>&1

echo ""
echo "[9] V\$PARAMETER (RESOURCE_LIMIT)"
$YASQL $CONN -A -q -c "SELECT NAME, VALUE FROM V\$PARAMETER WHERE NAME='resource_limit';" 2>&1

echo ""
echo "[10] DBA_TABLES (CHAIN_CNT)"
$YASQL $CONN -A -q -c "SELECT OWNER, TABLE_NAME, CHAIN_CNT FROM DBA_TABLES WHERE CHAIN_CNT > 0;" 2>&1

echo ""
echo "[11] V\$ARCHIVED_LOG (当天归档数)"
$YASQL $CONN -A -q -c "SELECT COUNT(*) FROM V\$ARCHIVED_LOG WHERE FIRST_TIME >= TRUNC(SYSDATE);" 2>&1

echo ""
echo "[12] V\$SQL (PERCENTILE - 测试)"
$YASQL $CONN -A -q -c "SELECT AVG(ELAPSED_TIME), PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY ELAPSED_TIME) FROM V\$SQL WHERE EXECUTIONS > 0;" 2>&1

echo ""
echo "[13] V\$SQLAREA (多维度 Top)"
$YASQL $CONN -A -q -c "SELECT SQL_ID, BUFFER_GETS, DISK_READS, EXECUTIONS FROM V\$SQLAREA ORDER BY BUFFER_GETS DESC FETCH FIRST 3 ROWS ONLY;" 2>&1

echo ""
echo "[14] V\$SESSION (按 USERNAME 分组)"
$YASQL $CONN -A -q -c "SELECT NVL(USERNAME,'(NULL)') AS USERNAME, COUNT(*) FROM V\$SESSION WHERE TYPE='USER' GROUP BY USERNAME ORDER BY 2 DESC;" 2>&1

echo ""
echo "[15] V\$SESSION (按 PROGRAM 分组)"
$YASQL $CONN -A -q -c "SELECT NVL(PROGRAM,'(NULL)') AS PROGRAM, COUNT(*) FROM V\$SESSION WHERE TYPE='USER' GROUP BY PROGRAM ORDER BY 2 DESC;" 2>&1

echo ""
echo "[16] DBA_OBJECTS (按类型统计 INVALID)"
$YASQL $CONN -A -q -c "SELECT OBJECT_TYPE, COUNT(*) FROM DBA_OBJECTS WHERE STATUS='INVALID' GROUP BY OBJECT_TYPE;" 2>&1

echo ""
echo "[17] DBA_UNDO_EXTENTS"
$YASQL $CONN -A -q -c "SELECT TABLESPACE_NAME, STATUS, COUNT(*), SUM(BYTES) FROM DBA_UNDO_EXTENTS GROUP BY TABLESPACE_NAME, STATUS;" 2>&1

echo ""
echo "[18] DBA_TEMP_FREE_SPACE"
$YASQL $CONN -A -q -c "SELECT * FROM DBA_TEMP_FREE_SPACE;" 2>&1

echo ""
echo "[19] V\$SQL (elapsed_time 分位数)"
$YASQL $CONN -A -q -c "SELECT COUNT(*) FROM V\$SQL WHERE ELAPSED_TIME > 0;" 2>&1

echo ""
echo "[20] V\$SQLAREA 列名检查"
$YASQL $CONN -A -q -c "SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='V\$SQLAREA';" 2>&1

echo ""
echo "=========================================="
echo "测试完成"
echo "=========================================="
