-- Nagios check_oracle_health 指标适配 — YashanDB 23.4 视图探查

-- 1. 检查无效对象
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS FROM DBA_OBJECTS WHERE STATUS='INVALID' ORDER BY OWNER;

-- 2. 检查无效索引
SELECT OWNER, INDEX_NAME, TABLE_NAME, STATUS FROM DBA_INDEXES WHERE STATUS='INVALID';

-- 3. 检查 STALE 统计信息相关表
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DBA_TABLES' OR TABLE_NAME = 'USER_TABLES' ORDER BY TABLE_NAME;

-- 4. 检查是否有 STALE_STATS 列（DBA_TAB_STATISTICS）
SELECT COUNT(*) FROM DBA_TAB_STATISTICS WHERE STALE_STATS = 'YES';

-- 5. 检查 DBA_TABLESPACE_USAGE_METRICS（表空间使用率）
SELECT * FROM DBA_TABLESPACE_USAGE_METRICS;

-- 6. 检查 DBA_TAB_MODIFICATIONS
SELECT * FROM DBA_TAB_MODIFICATIONS FETCH FIRST 3 ROWS ONLY;

-- 7. 检查段大小（DBA_SEGMENTS）
SELECT TABLESPACE_NAME, SUM(BYTES)/1024/1024 AS SIZE_MB FROM DBA_SEGMENTS GROUP BY TABLESPACE_NAME ORDER BY SIZE_MB DESC;

-- 8. 检查 V$FILESTAT（数据文件 I/O）
SELECT FILE#, PHYRDS, PHYWRTS, READTIM, WRITETIM FROM V$FILESTAT;

-- 9. 检查软解析相关统计项
SELECT NAME, VALUE FROM V$SYSSTAT WHERE NAME LIKE '%PARSE%';

-- 10. 检查 DBMS_STATS 是否可用
SELECT COUNT(*) FROM USER_OBJECTS WHERE OBJECT_NAME = 'DBMS_STATS';

-- 11. 检查闪回恢复区
SELECT NAME, SPACE_LIMIT, SPACE_USED, SPACE_RECLAIMABLE FROM V$RECOVERY_FILE_DEST;

-- 12. 检查 V$INSTANCE
SELECT INSTANCE_NAME, STATUS, STARTUP_TIME FROM V$INSTANCE;

-- 13. 检查数据文件 I/O 相关等待事件
SELECT EVENT, TOTAL_WAITS, TIME_WAITED FROM V$SYSTEM_EVENT WHERE EVENT LIKE '%db file%' ORDER BY TOTAL_WAITS DESC;

-- 14. 检查 buffer pool statistics
SELECT * FROM V$BUFFER_POOL_STATISTICS;

-- 15. 检查 DBA_DATA_FILES 的 MAXBYTES
SELECT TABLESPACE_NAME, FILE_NAME, BYTES, MAXBYTES, STATUS FROM DBA_DATA_FILES;
